---
name: deploy-prod

"on":
  push:
    branches: ["master"]

jobs:
  deploy-dev:
    runs-on: [self-hosted, vps76]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init
        run: |
          rm -rf .venv
          python3 -m venv .venv
          source .venv/bin/activate
          pip install wheel
          pip install -r requirements.txt

      - name: Clean up
        run: |
          source .venv/bin/activate
          make clean

      - name: Build
        run: |
          source .venv/bin/activate
          make html

      - name: Install
        run: |
          rm -rf /var/www/blog/_build/ /var/www/blog/_static/
          cp -rp _build _static /var/www/blog
