---
name: deploy-dev

"on":
  push:
    branches: ["dev"]

jobs:
  deploy-dev:
    runs-on: [self-hosted, dev-east]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Init
        run: |
          rm -rf .venv
          python3 -m venv .venv
          source .venv/bin/activate
          pip install wheel
          pip install -r requirements.txt

      - name: Clean up
        run: |
          source .venv/bin/activate
          make clean

      - name: Build
        env:
          NUTRA_BLOG_BASE_URL: https://dev.nutra.tk/blog
        run: |
          source .venv/bin/activate
          make html

      - name: Install
        run: |
          rm -rf /var/www/blog/*
          cp -rp output/* /var/www/blog/
