---
name: deploy-gh-pages

"on":
  push:
    branches: ["master"]

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare build (fix)
        run: git config --global --add safe.directory /github/workspace
      - name: Pelican to GitHub Pages
        uses: rehanhaider/pelican-to-github-pages@v1.2.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NUTRA_BLOG_BASE_URL: https://nutratech.blog.github.io
