---
name: deploy-prod

"on":
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-prod:
    runs-on: [self-hosted, prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Init
        run: |
          rm -rf .venv
          python3 -m venv .venv
          source .venv/bin/activate
          pip install wheel
          pip install -r requirements.txt

      - name: Clean up
        run: |
          source .venv/bin/activate
          make clean

      - name: Build
        env:
          NUTRA_BLOG_BASE_URL: https://nutra.tk/blog
        run: |
          source .venv/bin/activate
          make publish

      - name: Install
        run: |
          rm -rf /var/www/blog/*
          cp -rp output/* /var/www/blog/

      - name: Prepare GitHub pages
        run: |
          git checkout gh-pages
          # || git switch --orphan=gh-pages
          ls -lah
          git add -f output/
          git --no-pager log
          git pull
          git --no-pager log
          git commit --no-gpg-sign -m "[ci skip] Automated deployment to GitHub Pages on $(date +%s%3N)"
          git push --force --set-upstream origin gh-pages
